# Install clojure
ARG INSTALL_EXERCISM="true"
COPY custom-scripts/exercism/* /tmp/library-scripts/
RUN bash /tmp/library-scripts/install-exercism.sh "${USERNAME}" \
    && apt-get autoremove -y && apt-get clean -y && rm -rf /var/lib/apt/lists/* /tmp/library-scripts/